---
homeassistant:
  # load packages
  packages: !include_dir_named integrations

# def config ...
default_config:

# Text to speech
tts:
  - platform: google_translate
    base_url: !secret tts_base_url

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

webostv:
  host: !secret propaganda_host
  name: propagandaTV

vacuum:
  - platform: xiaomi_miio
    host: !secret s5_vacuum_host
    token: !secret s5_vacuum_token
    name: Robo Rooter

python_script:

http:
  ip_ban_enabled: True
  login_attempts_threshold: 5
  use_x_forwarded_for: True
  trusted_proxies: 0.0.0.0/0

recorder:
  auto_purge: True
  purge_keep_days: 7
  commit_interval: 5
  exclude:
    domains:
      - automation
      - updater
