---
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate
    base_url: !secret tts_base_url

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

webostv:
  host: !secret propaganda_host
  name: propagandaTV

vacuum:
  - platform: xiaomi_miio
    host: !secret s5_vacuum_host
    token: !secret s5_vacuum_token
    name: Robo Rooter

python_script:

http:
  ip_ban_enabled: True
  login_attempts_threshold: 5
  use_x_forwarded_for: True
  trusted_proxies: 0.0.0.0/0
