---
homeassistant:
  name: Home
  latitude: !secret zone_home_latitude
  longitude: !secret zone_home_longitude
  elevation: !secret zone_home_elevation
  time_zone: "Europe/Sofia"
  unit_system: metric
  # load packages
  packages: !include_dir_named integrations

# def config ...
default_config:

# Text to speech
tts:
  - platform: google_translate
    base_url: !secret tts_base_url

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

webostv:
  host: !secret propaganda_host
  name: propagandaTV

vacuum:
  - platform: xiaomi_miio
    host: !secret s5_vacuum_host
    token: !secret s5_vacuum_token
    name: Robo Rooter

python_script:
