---

rules:
  line-length:
    max: 120

ignore: |
  homeassistant-config/www/community
  homeassistant-config/custom_components
  homeassistant-config/blueprints/automation/homeassistant/notify_leaving_zone.yaml
