---
#####
# Triggers change of tariffs
# Used to switch between expensive/cheaper electricity tariff
#####

alias: 'change_day_night_tarif'
description: 'Change between day and night tarrifs (peak/offpeak)'
id: 681575b9-72cf-43c8-9d51-e6d4898c7cb0

trigger:
- platform: time
  at: '06:00:00'
- platform: time
  at: '22:00:00'

action:
- service: utility_meter.next_tariff
  entity_id: utility_meter.daily_energy
- service: utility_meter.next_tariff
  entity_id: utility_meter.monthly_energy
