---
# OTA related
esphome:
  on_boot:
    - text_sensor.template.publish:
        id: sensor_ota_status
        state: "IDLE"

ota:
  - platform: esphome
    password: !secret ota_password
    id: ota_id

    # OTA Automations
    on_begin:
      - text_sensor.template.publish:
          id: sensor_ota_status
          state: "In Progress"

    on_end:
      - text_sensor.template.publish:
          id: sensor_ota_status
          state: "IDLE"

text_sensor:
  - platform: template
    name: "${device_friendly_name} OTA Status"
    id: sensor_ota_status
