---
substitutions:
  wifi_reboot_timeout: 5min
  power_save_mode: LIGHT

wifi:
  # use_address: $ip
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password

  reboot_timeout: $wifi_reboot_timeout
  power_save_mode: ${power_save_mode}
  ap:
    password: !secret ap_password
