id: shellies_discovery
alias: Shellies Discovery
description: >-
  Generate necessary payloads to discover shellies
mode: queued
max: 999
trigger:
  platform: mqtt
  topic: shellies/announce
action:
  service: python_script.shellies_discovery
  data_template:
    id: '{{ trigger.payload_json.id }}'
    mac: '{{ trigger.payload_json.mac }}'
    fw_ver: '{{ trigger.payload_json.fw_ver }}'
    model: '{{ trigger.payload_json.model }}'
    shellyht-E00685:
      force_update_sensors: true
    shellyht-E00557:
      force_update_sensors: true
    shelly1pm-BA5659:
      relay-0: switch
    shellydw2-483FDA81E1D1:
      force_update_sensors: true
