---
id: '3b8d386c-4845-4c97-b81c-3c18a2cb33b0'
alias: 'Wash Cycle - Start'
description: 'Start the washing cycle'
trigger:
  platform: numeric_state
  entity_id: sensor.shelly_1pm_40F520016B7E_power_1
  above: '150'
  for: 00:02:00
condition: []
action:
  - service: input_boolean.turn_on
    data: {}
    entity_id: input_boolean.peralnia
mode: single
