---
id: 'cb42da92-5718-4be5-b0d0-93e93b27b9f2'
alias: 'Notify: washing machine cunsumables'
description: 'Notify that new consumables need to be bought'
trigger:
  platform: numeric_state
  entity_id: counter.kapsuli_prane
  below: '5'
condition: []
action:
- service: notify.persistent_notification
  data:
    message: Купи прах за пране
    title: Пералня
- service: notify.notify
  data:
    message: Купи Прах за пране
mode: single
