---
id: 'update-shelly-firmware'
alias: Update Shellies
mode: single
description: Update shellies firmware if/when available
trigger:
  - platform: state
    entity_id: group.shellies_firmware
    from: 'off'
    to: 'on'
action:
  - service: mqtt.publish
    data:
      topic: shellies/command
      payload: update_fw
