---
substitutions:
  project_name: "zeridon.unnamed-project"
  project_version: "0.0.0-dev"

esphome:
  name: ${name}
  name_add_mac_suffix: true
  project:
    name: ${project_name}
    version: ${project_version}

packages:
  wifi: !include common/wifi.yaml
  ota: !include common/ota.yaml
  sensors: !include common/sensors.yaml
  binary_sensors: !include common/binary_sensors.yaml
  time: !include common/time.yaml
  logger: !include common/logger.yaml
  api: !include common/api.yaml
  switches: !include common/switches.yaml
  buttons: !include common/buttons.yaml
  captive_portal: !include common/captive_portal.yaml
  web_server: !include common/web_server.yaml
