---
id: '96201aa6-923d-4196-a126-742f170220fa'
alias: Tumbledrier - ON/OFF
description: Handle tumbledrier states
mode: single
trigger:
  - platform: numeric_state
    entity_id: sensor.tumble_drier_power_0
    id: tumbledrier_on
    above: '4'
    for:
      hours: 0
      minutes: 2
      seconds: 0
      milliseconds: 0
  - platform: numeric_state
    entity_id: sensor.tumble_drier_power_0
    id: tumbledrier_off
    below: '10'
    for:
      hours: 0
      minutes: 2
      seconds: 0
      milliseconds: 0
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: tumbledrier_on
          - condition: state
            entity_id: input_boolean.sushilnia_raboti
            state: 'off'
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: input_boolean.sushilnia_raboti
      - conditions:
          - condition: trigger
            id: tumbledrier_off
          - condition: state
            entity_id: input_boolean.sushilnia_raboti
            state: 'on'
        sequence:
          - service: input_boolean.turn_off
            target:
              entity_id: input_boolean.sushilnia_raboti
    default: []
