---
id: '1609959023251'
alias: 'Turn kitchen Light on'
description: 'Turn the kitchen light on when family comes home'
trigger:
  - platform: state
    entity_id: group.family
    to: home
action:
  - type: turn_on
    device_id: 62478055d3445ad0cf56fa09dcde5128
    entity_id: light.kukhnenska_lampa
    domain: light
mode: single
