---
id: '1609959023251'
alias: 'Turn Light on'
description: 'Turn some lights on when family comes home'
trigger:
  - platform: state
    entity_id: group.family
    to: home
action:
  - type: turn_on
    device_id: ad4c1d8bfb64f18fc463e8f6c33aa33c
    entity_id: 95ee82417cede0b115cde0a2c21d2a9a
    domain: switch
mode: single
