# Describes the format for available zha services
execute:
  description: Execute ZHA Toolkit service (Examine the documentation or code to know which parameters are needed)
  fields:
    command:
      description: Command name
      example: scan_device
      required: true
      selector:
        select:
          options:
            - add_group
            - add_to_group
            - all_routes_and_neighbours
            - attr_read
            - attr_write
            - backup
            - bind_group
            - bind_ieee
            - conf_report
            - ezsp_add_key
            - ezsp_backup
            - ezsp_clear_keys
            - ezsp_get_config_value
            - ezsp_get_ieee_by_nwk
            - ezsp_get_keys
            - ezsp_get_policy
            - ezsp_get_token
            - ezsp_get_value
            - ezsp_set_channel
            - ezsp_start_mfg
            - get_groups
            - get_routes_and_neighbours
            - get_zll_groups
            - handle_join
            - ieee_ping
            - leave
            - ota_notify
            - rejoin
            - remove_all_groups
            - remove_from_group
            - remove_group
            - scan_device
            - sinope
            - unbind_coordinator
            - unbind_group
            - zcl_cmd
            - zdo_flood_parent_annce
            - zdo_join_with_code
            - zdo_scan_now
            - zdo_update_nwk_id
            - zigpy_deconz
            - znp_backup
            - znp_nvram_backup
            - znp_nvram_reset
            - znp_nvram_restore
            - znp_restore
    ieee:
      description: "Entity name,\ndevice name, or\nIEEE address of the node to execute command"
      example: "00:0d:6f:00:05:7d:2d:34"
      selector:
        entity:
          integration: zha
    command_data:
      description: data for the command (specific command. Example, second IEEE address for binding)
      example: "00:0d:6f:00:05:7d:2d:34"
      selector:
        text:
    manf:
      description: Manufacturer id
      selector:
        number:
          min: 1
          max: 0xFFFF
    cmd:
      description: Command Id (zcl_cmd)
      selector:
        number:
          min: 0
          max: 255 
    endpoint:
      description: target endpoint
      selector:
        number:
          min: 1
          max: 255 
    cluster:
      description: target cluster
      selector:
        number:
          min: 0
          max: 0xFFFF
    attribute:
      description: target attribute id (or name, accepted in most cases)
      selector:
        number:
          min: 0
          max: 0xFFFF
    attr_type:
      description: Attribute type (to write, ...)
      selector:
        number:
          min: 0
          max: 0xFFFF
    attr_val:
      description: Attribute value to write
      selector:
        text:
    min_interval:
      description: Minimum report interval (seconds)
      selector:
        number:
          min: 0
          max: 0xFFFF
    max_interval:
      description: Maximum report interval (seconds)
      selector:
        number:
          min: 0
          max: 0xFFFF
    reportable_change:
      description: Minimum change before reporting
      selector:
        number:
          min: 0
          max: 65535
    dir:
      description: Direction indicator, according to command
      selector:
        number:
          min: 0
          max: 1  
    tries:
      description: Number of times the zigbee packet should be attempted
      selector:
        number:
          min: 0 
          max: 255
    state_id:
      description: When defined, name of state to write the read attribute value to
      example: sensor.example
      selector:
        text:
    state_attr:
      description: When defined, attribute in state_id to write the read attribute value to.  Write to state value when missing (and state_id is defined)
      example: other_attr 
      selector:
        text:
    event_success:
      description: Event name in case of success (currently for attr_read, attr_write).  Has event data with relevant attributes.
      example: my_read_success_trigger_event
      selector:
        text:
    event_fail:
      description: Event name in case of failure (currently for attr_read, attr_write).  Has event data with relevant attributes.
      example: my_read_fail_trigger_event
      selector:
        text:
    event_done:
      description: Event name when the service call did all its work (either success or failure).  Has event data with relevant attributes.
      example: my_read_done_trigger_event
      selector:
        text:
    allow_create:
       description: Allow state creation (given by state_id) if it does not exist
       selector:
         boolean:
    read_before_write:
       description: "Read attribute before writing it (used with attr_write).  When the read value matches the value to write, no write is done  Defaults to True."
       selector:
         boolean:
    read_after_write:
       description: "Read attribute after writing.  Can be used to ensure the values match.  Defaults to True"
       selector:
         boolean:
    write_if_equal:
       description: "Force writing the attribute even if the read attribute already matches.  Defaults to False"
       selector:
         boolean:
    expect_reply:
       description: "Wait for/expect a reply (not used yet)"
       selector:
         boolean:
