---
id: '1634830528969'
alias: 'Bathroom night light - ON/OFF'
description: 'Handle night light based on movement'
mode: restart
trigger:
  platform: state
  entity_id: binary_sensor.zaetost_bania_occupancy
  from: "off"
  to: "on"
condition:
  - condition: time
    after: '21:00:00'
    before: '08:00:00'
action:
  - service: switch.turn_on
    target:
      entity_id: switch.lampa_bania
  - wait_for_trigger:
      platform: state
      entity_id: binary_sensor.zaetost_bania_occupancy
      from: "on"
      to: "off"
  - delay:
      minutes: 1
  - service: switch.turn_off
    target:
      entity_id: switch.lampa_bania
