---
id: 'fa635799-3993-421a-9cb1-1e4396bcee91'
alias: 'Kitchen fridge - OFF'
description: 'Set indicator the fridge is off'
trigger:
  platform: numeric_state
  entity_id: sensor.shelly_2_5_694435_power_0
  below: '1'
  for: 00:01:00
condition:
  - condition: state
    entity_id: input_boolean.kitchen_fridge
    state: 'on'
action:
  - service: input_boolean.turn_off
    data: {}
    entity_id: input_boolean.kitchen_fridge
mode: single
