---
sensor:
  - platform: template
    sensors:
      all_house_energy_usage:
        unit_of_measurement: 'kWh'
        value_template: >
          {#sum all sensors and add some static load due to shellies not self measuring and other #}
          {{
            (
              (states('sensor.shelly_1pm_40f520008838_energy_0') | float) +
              (states('sensor.shelly_1pm_40f52001721b_energy_0') | float) +
              (states('sensor.shelly_1pm_ba0ab9_energy_0') | float) +
              (states('sensor.shelly_1pm_ba5659_energy_0') | float)
            ) | round(2)
          }}
