---
description: Send notification on Home Assistant start
alias: system_start_notification
id: d23109a4-cf92-4de3-a77d-84535650144d
mode: single
trigger:
  platform: homeassistant
  event: start
action:
  - service: notify.notify
    data:
      title: HA Status
      message: Home Assistant is starting up
