---
description: Send notification on Home Assistant stop
alias: system_shutdown_notification
id: c6deb2c7-74be-47ee-8bf8-507f79f9ce9a
mode: single
trigger:
  - platform: homeassistant
    event: shutdown
action:
  - service: notify.notify
    data:
      title: HA Status
      message: Home Assistant is shutting down...
