id: '0c41c093-3bf7-46dc-b614-19f98b3971fc'
alias: Boiler ON - 18:30
description: 'Turn Boiler ON in the afternoon'
mode: single
trigger:
  - platform: time
    at: "18:30:00"
action:
  - type: turn_on
    device_id: 701873e4af114c9f61a6edbaea4938d8
    entity_id: switch.shelly_1pm_ba5659_relay_0
    domain: switch
