id: '7ed5622c-db37-4454-b1a8-a658ae54adff'
alias: Boiler OFF - 05:55
description: 'Turn Boiler OFF in the morning'
mode: single
trigger:
  - platform: time
    at: "05:55:00"
action:
  - type: turn_off
    device_id: 701873e4af114c9f61a6edbaea4938d8
    entity_id: switch.shelly_1pm_ba5659_relay_0
    domain: switch
