---
name: Home Assistant CI

# yamllint disable rule:line-length
on:
  push:
  pull_request:
  schedule:
    - cron: 0 12 * * *

jobs:

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Getting your configuration from GitHub
        uses: actions/checkout@v4
      - name: Running YAMLlint
        uses: "docker://pipelinecomponents/yamllint:latest"
        with:
          args: yamllint .

  remarklint:
    runs-on: ubuntu-latest
    steps:
      - name: Getting your configuration from GitHub
        uses: actions/checkout@v4
      - name: Running Remark lint
        uses: "docker://pipelinecomponents/remark-lint:latest"
        continue-on-error: true
        with:
          args: "remark --no-stdout --color --frail --use preset-lint-recommended ."

  home_assistant:
    runs-on: ubuntu-latest
    needs: [yamllint, remarklint]
    strategy:
      matrix:
        version: ["stable", "beta", "dev"]
    steps:
      - name: Getting your configuration from GitHub
        uses: actions/checkout@v4
      - name: Generate secrets
        run: ./scripts/hass-gen-ci-secrets.sh && mv homeassistant-config/ci-secrets.yaml homeassistant-config/secrets.yaml
      - name: Home Assistant Configuration check
        uses: frenck/action-home-assistant@v1.4.1
        with:
          path: ./homeassistant-config
          version: "${{ matrix.version }}"
